# Generated by Django 5.1.7 on 2025-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
