# Generated by Django 5.1.7 on 2025-04-21 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
