# Generated by Django 5.1.7 on 2025-04-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_patientappointment_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
