# Generated by Django 5.1.7 on 2025-04-21 06:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_delete_patientappointment'),
        ('doctors', '0004_timeslot_doctors_available_timeslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=15)),
                ('reason_to_visit', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.timeslot')),
            ],
            options={
                'unique_together': {('doctor', 'appointment_date', 'timeslot')},
            },
        ),
    ]
