# Generated by Django 5.1.7 on 2025-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_awards_doctors_publications_doctors_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_extraordinary',
            field=models.BooleanField(default=False),
        ),
    ]
