# Generated by Django 5.1.7 on 2025-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_timeslot_doctors_available_timeslots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='appointment_time',
            new_name='end_time',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='available_timeslots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'start_time', 'end_time', 'appointment_date')},
        ),
    ]
